name: "Build"

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build"
      run: make lin
    - name: "Create artifact"
      run: |
        tar -C ./csvfix/bin -czvf csvfix-${{ github.ref_name }}-linux.tar.gz csvfix
    - name: "Upload linux artifact"
      uses: softprops/action-gh-release@v1
      with:
        files: csvfix-${{ github.ref_name }}-linux.tar.gz
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build"
      run: make mac
    - name: "Create artifact"
      run: |
        zip -rllj csvfix-${{ github.ref_name }}-osx.zip ./csvfix/bin/csvfix
    - name: "Upload mac artifact"
      uses: softprops/action-gh-release@v1
      with:
        files: csvfix-${{ github.ref_name }}-osx.zip
  build_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build"
      run: make win
    - name: "Create release archive"
      shell: powershell
      run: |
        7z a "csvfix-${{ github.ref_name }}-win.zip" .\csvfix\bin\csvfix.exe
    - name: "Upload win artifact"
      uses: softprops/action-gh-release@v1
      with:
        files: csvfix-${{ github.ref_name }}-win.zip
